export const FETCH_PARAGRAPHS = 'FETCH_PARAGRAPHS';
export const FETCH_PARAGRAPHS_START = 'FETCH_PARAGRAPHS_START';
export const FETCH_PARAGRAPHS_SUCCESS = 'FETCH_PARAGRAPHS_SUCCESS';
export const FETCH_PARAGRAPHS_FAIL = 'FETCH_PARAGRAPHS_FAIL';

export const FETCH_PARAGRAPH = 'FETCH_PARAGRAPH';
export const FETCH_PARAGRAPH_START = 'FETCH_PARAGRAPH_START';
export const FETCH_PARAGRAPH_SUCCESS = 'FETCH_PARAGRAPH_SUCCESS';
export const FETCH_PARAGRAPH_FAIL = 'FETCH_PARAGRAPH_FAIL';
