export const FETCH_PARAGRAPHS = 'FETCH_PARAGRAPHS';
export const FETCH_PARAGRAPHS_START = 'FETCH_PARAGRAPHS_START';
export const FETCH_PARAGRAPHS_SUCCESS = 'FETCH_PARAGRAPHS_SUCCESS';
export const FETCH_PARAGRAPHS_FAIL = 'FETCH_PARAGRAPHS_FAIL';
